export const SPORT_TYPES = [
  {
    id: 'track',
    label: 'Dráha (Velodrome)',
    icon: '🏟️',
    requiresTrack: true,
    requiresGearing: true,
    modes: [
      { id: 'workout', label: 'Tréninková jednotka' },
      { id: 'race', label: 'Závod' },
      { id: 'test', label: 'Test / Měřený pokus (PB)' },
      { id: 'warmup_cooldown', label: 'Rozjetí / Vyjetí' },
    ],
    disciplines: [
      { id: 'f200', label: '200m s letmým startem (F200)', category: 'sprint' },
      { id: 'standing_start', label: 'Pevný start (500m / 1km)', category: 'sprint' },
      { id: 'match_sprint', label: 'Match Sprint (Rozjížďky)', category: 'sprint' },
      { id: 'keirin', label: 'Keirin', category: 'sprint' },
      { id: 'team_sprint', label: 'Team Sprint', category: 'sprint' },
      { id: 'individual_pursuit', label: 'Stíhací závod jednotlivců (IP)', category: 'endurance' },
      { id: 'team_pursuit', label: 'Stíhací závod družstev (TP)', category: 'endurance' },
      { id: 'points_race', label: 'Bodovací závod', category: 'endurance' },
      { id: 'scratch', label: 'Scratch', category: 'endurance' },
      { id: 'elimination', label: 'Vylučovací závod', category: 'endurance' },
      { id: 'tempo_race', label: 'Tempo Race / Omnium', category: 'endurance' },
      { id: 'madison', label: 'Madison', category: 'endurance' },
      { id: 'motor_paced', label: 'Derny / Vodič', category: 'special' },
    ],
  },
  {
    id: 'road',
    label: 'Silnice (Road)',
    icon: '🚴',
    requiresTrack: false,
    requiresGearing: false,
    modes: [
      { id: 'workout', label: 'Intervalový trénink' },
      { id: 'endurance', label: 'Základní vytrvalost (Z2)' },
      { id: 'race', label: 'Silniční závod / Kritérko' },
      { id: 'recovery', label: 'Regenerace / Vyjetí' },
    ],
    disciplines: [
      { id: 'road_race', label: 'Silniční závod' },
      { id: 'criterium', label: 'Kritérium' },
      { id: 'time_trial', label: 'Časovka jednotlivců' },
      { id: 'intervals_vo2', label: 'VO2 Max / Kopce' },
      { id: 'sprint_drills', label: 'Silniční sprinty / Nástupy' },
    ],
  },
  {
    id: 'gym',
    label: 'Posilovna (Gym / Strength)',
    icon: '🏋️‍♂️',
    requiresTrack: false,
    requiresGearing: false,
    modes: [
      { id: 'max_strength', label: 'Maximální síla (1-5 RM)' },
      { id: 'power_explosive', label: 'Výbušnost & Rychlost (Speed-Strength)' },
      { id: 'hypertrophy', label: 'Objemová příprava (Hypertrofie)' },
      { id: 'prehab_core', label: 'Core / Stabilita / Prevence' },
    ],
    disciplines: [
      { id: 'squats_focus', label: 'Dřepy (Zadní / Přední / Safety bar)' },
      { id: 'cleans_snatches', label: 'Vzpírání (Přemístění / Trh)' },
      { id: 'deadlifts_hex', label: 'Tahové cviky (Hex bar / Mrtvý tah)' },
      { id: 'plyometrics', label: 'Plyometrie & Odrazy' },
      { id: 'full_body_drills', label: 'Kruhový trénink celého těla' },
    ],
  },
  {
    id: 'roller_erg',
    label: 'Válce / Trenažér',
    icon: '🔄',
    requiresTrack: false,
    requiresGearing: true,
    modes: [
      { id: 'cadence_drills', label: 'Frekvenční trénink (Obrátky > 150 RPM)' },
      { id: 'erg_intervals', label: 'Wattbike / Trenažér úseky' },
      { id: 'warmup', label: 'Předzávodní rozjetí' },
    ],
    disciplines: [
      { id: 'spin_outs', label: 'Přetáčecí sprinty na lehký převod' },
      { id: 'torque_starts', label: 'Silové rozjezdy z nulové rychlosti' },
      { id: 'steady_roll', label: 'Vyjetí na válcích' },
    ],
  },
]